In [6]:
import numpy as np
x = [[123,23,43,123],[123,123,34,23],[23,234,234,234]]
np.array(x)



array([[123,  23,  43, 123],
       [123, 123,  34,  23],
       [ 23, 234, 234, 234]])

In [28]:
x = np.linspace
print(x)


<function linspace at 0x000001AC12107C80>


# Comandos Relacionados ao Random 

In [20]:
np.random.randn(10,10)


array([[ 0.71934598,  1.55369959,  0.60410557,  1.44949064,  0.95394119,
         0.21964049, -0.58854555, -1.06772194,  0.59840777, -0.13261017],
       [-1.02052519, -0.91343152, -0.13279902, -0.84891584, -0.82282813,
         0.09675587,  0.06540459, -1.0387814 ,  0.01324294,  1.60078186],
       [ 0.63434786,  0.48281947,  1.21772532,  0.06046792, -1.63494363,
         0.6679511 , -0.66552714,  0.98907255,  0.50119751, -2.05480543],
       [ 0.05394908, -0.89010686,  0.03131929,  0.91172329,  0.14322934,
        -1.05210751,  0.16887973,  0.7411778 ,  0.46557017,  0.88585432],
       [ 0.94700345, -0.48858139, -1.61653362,  0.87249144,  0.56706263,
         0.42051795, -0.78206721,  0.68154319,  0.97859283,  0.23543068],
       [ 2.04974449, -0.04231839,  0.31204361, -2.24375971, -2.39908123,
        -0.72494629, -0.26274077,  0.85151538,  0.28300475, -0.82949519],
       [ 1.45208387,  0.93205099, -0.55576084, -1.04179181, -2.76605277,
         1.41065224,  0.93511796, -0.58438545

In [21]:
x = np.random.randn(100)

In [27]:
x.reshape(5,20)


array([[ 0.11594081,  2.52603995,  0.66874841,  2.20288014, -0.01454325,
        -1.22229489,  0.74508993, -1.84985111, -0.37564683, -0.81806388,
         1.97474808, -1.05404713, -1.26939562, -1.8097673 ,  0.63970033,
        -0.18770229, -0.52525037,  0.81967884,  0.72741865,  0.81147407],
       [ 1.01597295, -1.9570955 ,  1.00578551,  3.48642473, -0.51860509,
        -0.43021222,  0.86556844,  0.8925985 , -0.82053783, -0.77696373,
        -1.43291259, -0.66376237,  1.06681393,  0.54319728, -1.18218607,
         1.22873428,  1.04904595, -1.96355954, -0.1038059 , -0.16803357],
       [ 1.22457655, -1.28529147, -0.4515364 ,  1.60978961,  1.28174018,
        -0.47549864, -0.03932421, -2.53956613,  0.10901384, -0.48482984,
         1.51100177,  0.71812363, -1.01235936, -0.15053433,  0.88655439,
         1.21367292,  1.43717765, -0.04114759,  0.58472799,  0.21501667],
       [ 0.11927528,  1.06565042, -0.32776493,  0.82165308, -0.20222395,
        -0.89596518, -0.09195671,  0.54756012, -

In [42]:
x = np.random.randn(100)
x = x.reshape(20,5)
print(x)

[[ 2.18597307  0.71775578  1.06923159  0.88715095 -1.3233627 ]
 [ 0.33279278 -0.80564559  0.61933174  0.08863599  2.57785698]
 [ 0.70514006  1.25126137 -0.54231472  1.04101209  3.27001987]
 [-0.88537126  1.29169851 -0.70333566 -0.59174053  0.3263491 ]
 [-0.08627793  0.28779186  2.09700102 -0.52655673  0.37993538]
 [-0.64613337 -0.33775602 -0.20196108  0.96175593  1.23583302]
 [-0.60786525 -0.31610152 -0.13891153 -0.05271475 -2.83798074]
 [-1.72959486 -0.00783366 -0.38776602  0.18330847  0.49495337]
 [ 0.97671419 -0.80837023  0.2504089   0.01937486  0.24523268]
 [ 0.13345023 -0.32329096 -1.46658965  0.23807733  1.41908535]
 [-1.21343919  0.09568605 -0.06591217 -0.95681255 -0.19940672]
 [-1.092371    0.20443087  2.42801245  0.39456454 -0.98955331]
 [-0.19888891  0.03678076 -0.89930095  0.38124538 -1.41521612]
 [-0.22093548  0.72852951  1.50050995 -0.2664148  -0.51294663]
 [-1.18814643  0.45513182 -1.02672185 -0.77550227 -0.15868121]
 [ 0.58763303 -1.15781935 -1.0204338  -1.41351122 -0.22

In [43]:
x[0]

array([ 2.18597307,  0.71775578,  1.06923159,  0.88715095, -1.3233627 ])

In [47]:
x.min()
x.argmin()



34

In [51]:
#boolean

y = np.arange(0,20,2)
boolean = y>5
print(boolean)

[False False False  True  True  True  True  True  True  True]


In [52]:
y[boolean]

array([ 6,  8, 10, 12, 14, 16, 18])

In [53]:
y[y>10]

array([12, 14, 16, 18])

In [54]:
(np.arange(10)/np.arange(10))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
np.arange(10)/3


array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])